import dayjs from 'dayjs/esm';

export interface ICourtCase {
  id: number;
  code?: number | null;
  caseDinank?: dayjs.Dayjs | null;
  bankName?: string | null;
  talukaName?: string | null;
  talukaCode?: number | null;
  sabasadSavingAccNo?: string | null;
  sabasadName?: string | null;
  sabasadAddress?: string | null;
  karjPrakar?: string | null;
  vasuliAdhikari?: string | null;
  ekunJama?: number | null;
  baki?: number | null;
  arOffice?: string | null;
  ekunVyaj?: number | null;
  jamaVyaj?: number | null;
  dandVyaj?: number | null;
  karjRakkam?: number | null;
  thakDinnank?: dayjs.Dayjs | null;
  karjDinnank?: dayjs.Dayjs | null;
  mudatSampteDinank?: dayjs.Dayjs | null;
  mudat?: string | null;
  vyaj?: string | null;
  haptaRakkam?: number | null;
  shakhaVevsthapak?: string | null;
  suchak?: string | null;
  anumodak?: string | null;
  dava?: number | null;
  vyajDar?: number | null;
  sarcharge?: number | null;
  jyadaVyaj?: number | null;
  yeneVyaj?: number | null;
  vasuliKharch?: number | null;
  etharKharch?: number | null;
  vima?: number | null;
  notice?: number | null;
  tharavNumber?: number | null;
  tharavDinank?: dayjs.Dayjs | null;
  vishayKramank?: number | null;
  noticeOne?: dayjs.Dayjs | null;
  noticeTwo?: dayjs.Dayjs | null;
  war?: string | null;
  vel?: string | null;
  jamindarOne?: string | null;
  jamindarOneAddress?: string | null;
  jamindarTwo?: string | null;
  jamindarTwoAddress?: string | null;
  taranType?: string | null;
  taranDetails?: string | null;
}

export type NewCourtCase = Omit<ICourtCase, 'id'> & { id: null };
