import { IIssPortalFile } from 'app/entities/iss-portal-file/iss-portal-file.model';

export interface IIssFileParser {
  id: number;
  financialYear?: string | null;
  bankName?: string | null;
  bankCode?: string | null;
  branchName?: string | null;
  branchCode?: string | null;
  schemeWiseBranchCode?: string | null;
  ifsc?: string | null;
  loanAccountNumberkcc?: string | null;
  farmerName?: string | null;
  gender?: string | null;
  aadharNumber?: string | null;
  dateofBirth?: string | null;
  ageAtTimeOfSanction?: string | null;
  mobileNo?: string | null;
  farmersCategory?: string | null;
  farmerType?: string | null;
  socialCategory?: string | null;
  relativeType?: string | null;
  relativeName?: string | null;
  stateName?: string | null;
  stateCode?: string | null;
  districtName?: string | null;
  districtCode?: string | null;
  blockCode?: string | null;
  blockName?: string | null;
  villageCode?: string | null;
  villageName?: string | null;
  address?: string | null;
  pinCode?: string | null;
  accountType?: string | null;
  accountNumber?: string | null;
  pacsName?: string | null;
  pacsNumber?: string | null;
  accountHolderType?: string | null;
  primaryOccupation?: string | null;
  loanSactionDate?: string | null;
  loanSanctionAmount?: string | null;
  tenureOFLoan?: string | null;
  dateOfOverDuePayment?: string | null;
  cropName?: string | null;
  surveyNo?: string | null;
  satBaraSubsurveyNo?: string | null;
  seasonName?: string | null;
  areaHect?: string | null;
  landType?: string | null;
  disbursementDate?: string | null;
  disburseAmount?: string | null;
  maturityLoanDate?: string | null;
  recoveryAmountPrinciple?: string | null;
  recoveryAmountInterest?: string | null;
  recoveryDate?: string | null;
  issPortalFile?: Pick<IIssPortalFile, 'id' | 'fileName'> | null;
}

export type NewIssFileParser = Omit<IIssFileParser, 'id'> & { id: null };
