import dayjs from 'dayjs/esm';

import { IKamalSociety, NewKamalSociety } from './kamal-society.model';

export const sampleWithRequiredData: IKamalSociety = {
  id: 26087,
};

export const sampleWithPartialData: IKamalSociety = {
  id: 29033,
  pacsNumber: 57050,
  zindagiDate: dayjs('2024-01-23T18:40'),
  zindagiDateMr: 'Checking Bedfordshire local',
  village1Mr: 'up Executive',
  village2: 'red Cotton',
  village3: 'Future Concrete',
  totalNonMem: 98856,
  totalNonMemMr: 'payment Small',
  memVasulpatra: 58098,
  memVasulpatraMr: 'copying bypass',
  memVasulMr: 'Territory task-force',
  bankDueMr: 'green',
  bankDueper: 94732,
  bankDueperMr: 'Sleek plug-and-play',
  bankVasulpatra: 95713,
  bankVasulpatraMr: 'Avon web Intelligent',
  bankVasulMr: 'PCI',
  shareCapital: 18773,
  funds: 85408,
  deposit: 7196,
  payableMr: 'International',
  cashInHand: 20826,
  investmentMr: 'Kansas',
  deadStock: 35502,
  deadStockMr: 'Outdoors SCSI',
  loss: 30458,
  lossMr: 'Applications Future Quetzal',
  totalBagayatMr: 'Accountability De-engineered recontextualize',
};

export const sampleWithFullData: IKamalSociety = {
  id: 18609,
  pacsNumber: 64907,
  zindagiDate: dayjs('2024-01-23T19:28'),
  zindagiDateMr: 'protocol',
  village1: 'Fords',
  village1Mr: 'Optimization Liaison Self-enabling',
  village2: '1080p wireless',
  village2Mr: 'indigo redefine orchestrate',
  village3: 'Account ROI Rustic',
  village3Mr: 'Buckinghamshire compressing connect',
  totalLand: 84652,
  totalLandMr: 'content extensible',
  totalMem: 84256,
  totalMemMr: 'navigating Loan Georgia',
  totalNonMem: 53708,
  totalNonMemMr: 'Regional user-facing online',
  totalGMem: 69997,
  totalGMemMr: 'SCSI',
  memLoan: 78042,
  memLoanMr: 'Savings',
  memDue: 19672,
  memDueMr: 'driver XML Account',
  memDueper: 89673,
  memDueperMr: 'Berkshire Designer',
  memVasulpatra: 66273,
  memVasulpatraMr: 'Unbranded Specialist',
  memVasul: 440,
  memVasulMr: 'generating niches Buckinghamshire',
  memVasulPer: 58610,
  memVasulPerMr: 'Plastic',
  bankLoan: 30561,
  bankLoanMr: 'interface interface Intelligent',
  bankDue: 47052,
  bankDueMr: 'deposit',
  bankDueper: 52389,
  bankDueperMr: 'Krone Product',
  bankVasulpatra: 84497,
  bankVasulpatraMr: 'Nevada Iceland Cheese',
  bankVasul: 59440,
  bankVasulMr: 'reboot Cambridgeshire Progressive',
  bankVasulPer: 50591,
  bankVasulPerMr: 'Cheese granular',
  shareCapital: 69929,
  shareCapitalMr: 'incubate',
  share: 60571,
  shareMr: '1080p',
  funds: 157,
  fundsMr: 'XML calculating',
  deposit: 20873,
  depositMr: 'Consultant',
  payable: 47952,
  payableMr: 'Branding Customer Account',
  profit: 17743,
  profitMr: 'online',
  cashInHand: 27608,
  cashInHandMr: 'unleash e-business bypass',
  investment: 14529,
  investmentMr: 'Steel',
  deadStock: 2771,
  deadStockMr: 'Concrete Rufiyaa Integration',
  otherPay: 7844,
  otherPayMr: 'teal maximized',
  loss: 97960,
  lossMr: 'Principal',
  totalBagayat: 8466,
  totalBagayatMr: 'orchid',
  totalJirayat: 80155,
  totalJirayatMr: 'Horizontal',
};

export const sampleWithNewData: NewKamalSociety = {
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
