import dayjs from 'dayjs/esm';

import { IKamalSociety, NewKamalSociety } from './kamal-society.model';

export const sampleWithRequiredData: IKamalSociety = {
  id: 26087,
  financialYear: 'invoice Agent',
};

export const sampleWithPartialData: IKamalSociety = {
  id: 48082,
  financialYear: 'Alabama',
  kmDate: dayjs('2024-01-31T18:22'),
  pacsNumber: 'invoice',
  pacsName: 'Congo',
  govTapasaniDate: dayjs('2024-02-01T09:43'),
  govTapasaniDateMr: 'matrix',
  sansthaTapasaniDateMr: 'intermediate black Nigeria',
  nonMemberFarmer: 'Small Nebraska visionary',
  talebandDate: dayjs('2024-02-01T10:26'),
  memLoan: 'Borders Kansas',
  memDue: 'Electronics',
  memVasuli: 'Branding',
  bankLoan: 'flexibility lavender',
  bankVasuliPer: 'Shirt Marketing',
  liabilityVasulShareCapital: 'enhance',
  liabilitySpareFund: 'Islands Fish',
  liabilityOtherPayable: 'Plastic',
  assetInvestment: 'Outdoors SCSI',
  assetDeadStock: 'parse',
  assetOtherReceivable: 'Future',
  assetLoss: 'hub Accountability De-engineered',
  villageCode: 'Assistant invoice',
  pacsVerifiedFlag: true,
  headOfficeVerifiedFlag: false,
  branchVerifiedBy: 'Practical',
  branchVerifiedDate: dayjs('2024-01-31T17:01'),
  headOfficeVerifiedBy: 'Optimization Liaison Self-enabling',
  headOfficeVerifiedDate: dayjs('2024-01-31T22:08'),
};

export const sampleWithFullData: IKamalSociety = {
  id: 81147,
  financialYear: 'schemas Representative auxiliary',
  kmDate: dayjs('2024-01-31T13:18'),
  kmDateMr: 'orchestrate THX',
  kmFromDate: dayjs('2024-01-31T19:51'),
  kmFromDateMr: 'Assimilated Keyboard',
  kmToDate: dayjs('2024-02-01T00:33'),
  kmToDateMr: 'Sports scale optical',
  pacsNumber: 'e-tailers Account',
  pacsName: 'navigating Loan Georgia',
  branchId: 53708,
  branchName: 'Regional user-facing online',
  talukaId: 69997,
  talukaName: 'SCSI',
  zindagiPatrakDate: dayjs('2024-01-31T17:49'),
  zindagiPatrakDateMr: 'Savings',
  bankTapasaniDate: dayjs('2024-02-01T07:50'),
  bankTapasaniDateMr: 'driver XML Account',
  govTapasaniDate: dayjs('2024-01-31T15:02'),
  govTapasaniDateMr: 'Berkshire Designer',
  sansthaTapasaniDate: dayjs('2024-01-31T20:39'),
  sansthaTapasaniDateMr: 'Unbranded Specialist',
  totalLand: 'neural',
  bagayat: 'niches',
  jirayat: 'redundant budgetary',
  totalFarmer: 'workforce',
  memberFarmer: 'mindshare approach',
  nonMemberFarmer: 'Canyon Advanced',
  talebandDate: dayjs('2024-02-01T02:56'),
  memLoan: 'Account emulation Planner',
  memDue: 'Iceland Cheese',
  memVasuli: 'Forward Central',
  memVasuliPer: 'Progressive',
  bankLoan: 'orchestrate Money',
  bankDue: 'Azerbaijanian',
  bankVasuli: 'multi-byte 1080p',
  bankVasuliPer: 'Cambridgeshire',
  balanceSheetDate: dayjs('2024-02-01T03:12'),
  balanceSheetDateMr: 'Moldovan Frozen Fresh',
  liabilityAdhikrutShareCapital: 'Customer Account Ball',
  liabilityVasulShareCapital: 'open-source unleash',
  liabilityFund: 'Bacon Handcrafted',
  liabilitySpareFund: 'Steel',
  liabilityDeposite: 'Manat',
  liabilityBalanceSheetBankLoan: 'RSS',
  liabilityOtherPayable: 'collaborative Centralized',
  liabilityProfit: 'maroon',
  assetCash: 'mobile Principal',
  assetInvestment: 'Bike',
  assetImaratFund: 'open-source web-enabled',
  assetMemberLoan: 'models',
  assetDeadStock: 'Salad',
  assetOtherReceivable: 'Research',
  assetLoss: 'Hong Unbranded Specialist',
  totalLiability: 'copying middleware',
  totalAsset: 'overriding',
  villageCode: 'reboot infomediaries mobile',
  pacsVerifiedFlag: true,
  branchVerifiedFlag: false,
  headOfficeVerifiedFlag: false,
  divisionalOfficeVerifiedFlag: false,
  isSupplimenteryFlag: true,
  sansthaTapasaniVarg: 'Pound',
  branchVerifiedBy: 'Bike open-source',
  branchVerifiedDate: dayjs('2024-02-01T04:38'),
  headOfficeVerifiedBy: 'Cross-platform',
  headOfficeVerifiedDate: dayjs('2024-02-01T11:56'),
  divisionalOfficeVerifiedBy: 'SMTP bleeding-edge',
  divisionalOfficeVerifiedDate: dayjs('2024-02-01T01:03'),
  doshPurtataDate: dayjs('2024-02-01T09:40'),
  gambhirDosh: 'Concrete',
};

export const sampleWithNewData: NewKamalSociety = {
  financialYear: 'extend',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
